name: Build oci-ping image

on:
  push:
    paths: ['oci-ping/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: xsp.ocir.io
          username: axfazd56plva/wangsenhu@gmail.com
          password: ${{ secrets.OCIR_TOKEN }}

      - name: Build and Push (AMD64)
        run: |
          docker build --platform linux/amd64 \
            -t xsp.ocir.io/axfazd56plva/gsd-scripts/oci-ping:latest \
            oci-ping/
          docker push xsp.ocir.io/axfazd56plva/gsd-scripts/oci-ping:latest
